### ISSUE TITLE
Improvement: Add Error Handling and Logging to Archive Processing Functions

### ISSUE THREAD

**Issue by finewiki** [HydraDragonAntivirus/ExelaV2StealerDecompiler#1]
Currently, the code processes different types of archives and files, including ZIP files, PE files, and WinRAR SFX archives, but it lacks consistent error handling and logging for various edge cases. For example:

Error handling is present, but some functions could be improved to handle specific exceptions more effectively.
Logging could be more detailed to provide insight into what happens at each stage, especially when extracting or processing files.

**Comment by HydraDragonAntivirus** [comment]
I lately see that because I reported someone and he got banned but he answered me but I can't see his answer.

**Comment by finewiki** [comment]
@HydraDragonAntivirus No problem, instead I can edit the code in the repo for you and fork it as a file. Would you like that?

**Comment by HydraDragonAntivirus** [comment]
Okay. Thank you! I will check your pull request.

**Comment by finewiki** [comment]
@HydraDragonAntivirus  You can help develop such projects by following me.
